apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:gerx24/gitops
    targetRevision: main
    path: core/ops-core
    helm:
      releaseName: app-of-apps
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
  - group: "*"
    kind: Application
    jsonPointers:
    - /spec/syncPolicy
