apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenants
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: core
  source:
    repoURL: git@github.com:gerx24/gitops
    path: core/tenants
    targetRevision: core
    helm:
      releaseName: tenants
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: '*'
      kind: Application
      jsonPointers:
        - /spec/syncPolicy
