---
apiVersion: v1
kind: Secret
metadata:
  name: germoral-sandbox-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:gerx24/gitops.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDA+OY84zUqmOGNGh0smQ+HZN/p53oT9HHLuhQDfbtk2gAAAKDN//Yqzf/2
    KgAAAAtzc2gtZWQyNTUxOQAAACDA+OY84zUqmOGNGh0smQ+HZN/p53oT9HHLuhQDfbtk2g
    AAAEAOtQID0FsDRRdluk5KNEKHhSACq6ao6dG9oI0T6UBmacD45jzjNSqY4Y0aHSyZD4dk
    3+nnehP0ccu6FAN9u2TaAAAAGmdlcm1vcmFsX3NhbmRib3hAZXN0ZWUuY29tAQID
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"