---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-13"
spec:
  dataFrom:
  - extract:
      key: {{ .Values.secret.secretkey}}
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: {{ .Values.secret.secretname}}
    template:
      engineVersion: v2
      type: Opaque