{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crdb-to-postgres.serviceAccountName" . }}
  labels:
    {{- include "crdb-to-postgres.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::161580959359:role/crdb-to-postgres-usva-role
{{- end }}
