Trust:
# {
#     "Version": "2012-10-17",
#     "Statement": [
#         {
#             "Sid": "",
#             "Effect": "Allow",
#             "Principal": {
#                 "Federated": "arn:aws:iam::183903597125:oidc-provider/token.actions.githubusercontent.com"
#             },
#             "Action": "sts:AssumeRoleWithWebIdentity",
#             "Condition": {
#                 "StringEquals": {
#                     "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
#                 },
#                 "StringLike": {
#                     "token.actions.githubusercontent.com:sub": [
#                         "repo:elc-online/germoral-sandbox:ref:refs/heads/main",
#                         "repo:elc-online/gerx24:ref:refs/heads/main"
#                     ]
#                 }
#             }
#         }
#     ]
# }

Policy: postgres-db-int-refresh-policy
# {
#     "Version": "2012-10-17",
#     "Statement": [
#         {
#             "Effect": "Allow",
#             "Action": [
#                 "eks:DescribeCluster",
#                 "eks:ListClusters",
#                 "eks:AccessKubernetesApi"
#             ],
#             "Resource": "arn:aws:eks:us-east-1:183903597125:cluster/int-usva-pincer-project"
#         },
#         {
#             "Effect": "Allow",
#             "Action": [
#                 "sts:AssumeRole"
#             ],
#             "Resource": "*"
#         }
#     ]
# }

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gerx24-db-refresh
  namespace: gerx24-db-refresh
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::183903597125:role/postgres-db-int-refresh-IRSA

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gerx24-db-refresh
  name: gerx24-db-refresh-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gerx24-db-refresh-rolebinding
  namespace: gerx24-db-refresh
subjects:
  - kind: User
    name: github:ci-gerx24
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: gerx24-db-refresh-role
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vulca-db-refresh-int
  namespace: gerx24-db-refresh
  annotations:
    argocd.argoproj.io/sync-wave: "-12"
spec:
  dataFrom:
  - extract:
      key: eks-int-usva-pincer-project/vulca-db-refresh-int
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: gerx24-db-refresh-int
    template:
      engineVersion: v2
      type: Opaque