name: Build runner image

on:
  push:
    branches:
      - main
    paths:
      - "runner/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    strategy:
      matrix:
        platform: ["amd64", "arm64"]
    outputs:
      short_sha: ${{ steps.short-sha.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - id: short-sha
        name: calculate short sha
        run: echo "short_sha=3.0.0" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: name=gerx24/runner-tools/centos
          tags: type=raw,value=${{ steps.short-sha.outputs.short_sha  }}-${{ matrix.platform }}

      - name: 🐳 Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: runner/Dockerfile
          push: true
          platforms: linux/${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }},mode=max

  postbuild:
    needs: ["build"]
    permissions:
      id-token: write
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and Push Docker Manifest
        run: |
          docker buildx imagetools create \
            --tag gerx24/runner-tools/centos:${{ needs.build.outputs.short_sha  }} \
            gerx24/runner-tools/centos:${{ needs.build.outputs.short_sha  }}-amd64 \
            gerx24/runner-tools/centos:${{ needs.build.outputs.short_sha  }}-arm64
