name: Deploy kafka-client

on:
  push:
    branches:
      - core
    paths:
      - "runner/**"

jobs:
  build:
    runs-on: ${{ matrix.platform == 'amd64' && 'k8s-mte-amd64' || 'k8s-mte-arm64' }}
    permissions:
      id-token: write
      contents: read
      packages: write
    strategy:
      matrix:
        platform: ["amd64", "arm64"]
    outputs:
      short_sha: ${{ steps.short-sha.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - id: short-sha
        name: calculate short sha
        run: echo "short_sha=latest" >> "$GITHUB_OUTPUT"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: name=ghcr.io/${{ github.repository }}/kafka-client
          tags: type=raw,value=${{ steps.short-sha.outputs.short_sha  }}-${{ matrix.platform }}

      - name: 🐳 Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: kafka_client/Dockerfile
          push: true
          platforms: linux/${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }},mode=max

  postbuild:
    needs: ["build"]
    permissions:
      id-token: write
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and Push Docker Manifest
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository }}/kafka-client:${{ needs.build.outputs.short_sha  }} \
            ghcr.io/${{ github.repository }}/kafka-client:${{ needs.build.outputs.short_sha  }}-amd64 \
            ghcr.io/${{ github.repository }}/kafka-client:${{ needs.build.outputs.short_sha  }}-arm64
